### ISSUE TITLE
ナビゲーションバータイトルの修正<会話ネタ編集画面>

### ISSUE THREAD

**Issue by Shinobu686** [Team-KARIYUSHI/TalkStock#143]
×ボタンなどモーダル遷移時のものが出てきてしまっているので修正する
<br>
<img width="400" alt="スクリーンショット 2021-03-26 0 37 14" src="https://user-images.githubusercontent.com/70428953/112503830-97883e80-8dce-11eb-84c9-3413d7b5f165.png">

**Comment by king-kazu39** [comment]
## 作業内容
[issue#138](https://github.com/Team-KARIYUSHI/TalkStock/issues/138)で対応したんだけど、
1画面で登録画面と編集画面の使い回しが難しいと判断したので、
Viewを2つ作ることにします

## 作業内容詳細
- [ ] TopicEditViewのファイル名とクラス名をTopicCreateViewに戻します。
- [ ] TopicCreateViewをTopicCreateViewにした時の下記変数２つを削除
※呼び出し元の変更を加えたところも直しましょう
```
var barTitle: String
var buttonTitle: String
```

- [ ] TopicEditViewというファイル名、クラス名でSwiftUIファイルを追加します
- [ ] TopicCreateViewのクラス内のコードをコピーしてTopicEditViewに写します
- [ ] TopicCreateViewに書いていたNavigationViewの部分とnavigationItem(バツボタンを追加している部分)を削除します。

## 動作確認
- [ ] 会話ネタタブバーTop画面のセルをタップし、ナビゲーション遷移して編集画面に移ります。
- [ ] ナビゲーションバーのバックボタンのみ表示され、
バツボタンバーが出てこない、ナビゲーションバーが下がるような表示ならないなど、
レイアウトがおかしくないことを確認して下さい
